[tool.poetry]
name = "anitrac"
version = "0.1.0"
description = ""
authors = ["marquel-rogers <144250049+marquel-rogers@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
